/**
 * Explosion Diagram Data Persistence Storage
 * Used for tracking generated objects and gallery
 */

import fs from "fs";
import path from "path";

export const DATA_DIR = path.join(process.cwd(), ".data");
export const EXPLOSION_INDEX_FILE = path.join(DATA_DIR, "explosion-index.json");
export const EXPLOSION_GALLERY_FILE = path.join(DATA_DIR, "explosion-gallery.json");

export interface ExplosionComponent {
  id: number;
  name: string;
  description: string;
  layer: number;
}

export interface ExplosionResult {
  id: string;
  objectName: string;
  components: ExplosionComponent[];
  imageUrl?: string;
  imageBase64?: string;
  prompt?: string;
  style: "realistic" | "diagram" | "technical";
  aspectRatio: string;
  createdAt: string;
  isAutoGenerated: boolean;
}

export interface ExplosionIndex {
  generatedObjects: string[]; // 已生成的物件名稱列表
  lastCronRun: string | null; // 上次 Cron 執行時間
  totalGenerated: number; // 總共生成的數量
  cronEnabled: boolean; // Cron 是否啟用
}

// Default object list - 50 common objects
export const DEFAULT_OBJECTS = [
  // Food
  "Burger", "Pizza", "Sushi", "Fried Chicken", "Pasta",
  // Electronics
  "Smartphone", "Laptop", "Tablet", "Smartwatch", "Headphones",
  "Camera", "Drone", "Gamepad", "Mechanical Keyboard", "Mouse",
  // Vehicles
  "Car", "Motorcycle", "Bicycle", "Train", "Airplane",
  // Daily Items
  "Watch", "Wallet", "Backpack", "Umbrella", "Luggage",
  "Glasses", "Hat", "Shoes", "Bicycle Helmet", "Camera Bag",
  // Furniture
  "Office Chair", "Desk", "Bed", "Wardrobe", "Bookshelf",
  // Instruments
  "Guitar", "Piano", "Drum Set", "Violin", "Saxophone",
  // Sports Equipment
  "Basketball", "Football", "Tennis Racket", "Golf Club", "Snowboard",
  // Kitchen Appliances
  "Coffee Machine", "Toaster", "Blender", "Rice Cooker", "Air Fryer",
];

// 確保資料目錄存在
function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
}

// 讀取索引
export function loadExplosionIndex(): ExplosionIndex {
  ensureDataDir();
  try {
    if (fs.existsSync(EXPLOSION_INDEX_FILE)) {
      const data = fs.readFileSync(EXPLOSION_INDEX_FILE, "utf-8");
      return JSON.parse(data);
    }
  } catch (error) {
    console.error("[ExplosionStore] 讀取索引失敗:", error);
  }
  return {
    generatedObjects: [],
    lastCronRun: null,
    totalGenerated: 0,
    cronEnabled: true,
  };
}

// 儲存索引
export function saveExplosionIndex(index: ExplosionIndex): void {
  ensureDataDir();
  try {
    fs.writeFileSync(EXPLOSION_INDEX_FILE, JSON.stringify(index, null, 2), "utf-8");
  } catch (error) {
    console.error("[ExplosionStore] 儲存索引失敗:", error);
  }
}

// 讀取圖庫
export function loadExplosionGallery(): ExplosionResult[] {
  ensureDataDir();
  try {
    if (fs.existsSync(EXPLOSION_GALLERY_FILE)) {
      const data = fs.readFileSync(EXPLOSION_GALLERY_FILE, "utf-8");
      return JSON.parse(data);
    }
  } catch (error) {
    console.error("[ExplosionStore] 讀取圖庫失敗:", error);
  }
  return [];
}

// 儲存圖庫
export function saveExplosionGallery(gallery: ExplosionResult[]): void {
  ensureDataDir();
  try {
    fs.writeFileSync(EXPLOSION_GALLERY_FILE, JSON.stringify(gallery, null, 2), "utf-8");
  } catch (error) {
    console.error("[ExplosionStore] 儲存圖庫失敗:", error);
  }
}

// 新增到圖庫
export function addToExplosionGallery(item: ExplosionResult): void {
  const gallery = loadExplosionGallery();
  gallery.unshift(item); // 新增到最前面
  saveExplosionGallery(gallery);
  console.log(`[ExplosionStore] 已新增到圖庫: ${item.objectName}`);
}

// 取得待生成的物件（尚未生成過的）
export function getPendingObjects(count: number = 40): string[] {
  const index = loadExplosionIndex();
  const pending: string[] = [];

  for (const obj of DEFAULT_OBJECTS) {
    if (!index.generatedObjects.includes(obj.toLowerCase())) {
      pending.push(obj);
      if (pending.length >= count) break;
    }
  }

  return pending;
}

// 標記物件為已生成
export function markObjectAsGenerated(objectName: string): void {
  const index = loadExplosionIndex();
  const key = objectName.toLowerCase();
  if (!index.generatedObjects.includes(key)) {
    index.generatedObjects.push(key);
    index.totalGenerated++;
    saveExplosionIndex(index);
  }
}

// 更新最後執行時間
export function updateLastCronRun(): void {
  const index = loadExplosionIndex();
  index.lastCronRun = new Date().toISOString();
  saveExplosionIndex(index);
}

// 檢查是否應該執行 Cron（每 20 小時）
export function shouldRunCron(): boolean {
  const index = loadExplosionIndex();
  if (!index.cronEnabled) return false;
  if (!index.lastCronRun) return true;

  const lastRun = new Date(index.lastCronRun);
  const now = new Date();
  const hoursSinceLastRun = (now.getTime() - lastRun.getTime()) / (1000 * 60 * 60);

  return hoursSinceLastRun >= 20;
}

// 啟用/停用 Cron
export function setCronEnabled(enabled: boolean): void {
  const index = loadExplosionIndex();
  index.cronEnabled = enabled;
  saveExplosionIndex(index);
}

// Generate components based on object name
export function generateComponentsForObject(object: string, count: number = 6): ExplosionComponent[] {
  const componentNames: Record<string, string[]> = {
    "burger": ["Top Bun", "Lettuce Leaf", "Tomato Slice", "Beef Patty", "Melted Cheese", "Onion Ring", "Bottom Bun"],
    "pizza": ["Pepperoni", "Mozzarella Cheese", "Tomato Sauce", "Mushroom Slices", "Green Pepper Strips", "Crust Base"],
    "sushi": ["Vinegar Rice", "Salmon Slice", "Avocado Slice", "Cucumber", "Nori Sheet", "Wasabi"],
    "fried chicken": ["Crispy Skin", "Tender Chicken Chunk", "Black Pepper", "Lemon Wedge", "Fries", "Sauce"],
    "pasta": ["Tomato Meat Sauce", "Pasta Noodles", "Parmesan Cheese", "Basil Leaves", "Olive Oil", "Garlic Slice"],
    "smartphone": ["Screen Panel", "Touch Module", "Mainboard", "Battery Component", "Camera Module", "Rear Frame", "Port Part"],
    "laptop": ["Screen Assembly", "Keyboard Panel", "Trackpad Module", "Motherboard Chip", "Cooling Fan", "Battery Module", "Bottom Frame"],
    "tablet": ["Touch Screen", "Display Panel", "Mainboard", "Battery Module", "Camera Module", "Metal Frame"],
    "smartwatch": ["Watch Face Panel", "AMOLED Screen", "Movement Component", "Battery Cell", "Strap Connector", "Rear Cover"],
    "headphones": ["Headband Bracket", "Earcup Shell", "Driver Unit", "Microphone Module", "Earpad Cushion", "Adjust Joint"],
    "camera": ["Lens Hood", "Lens Group", "Shutter Module", "Image Sensor", "Image Processor", "Body Frame", "Memory Card Slot"],
    "drone": ["Propeller Blade", "Body Frame", "Motor Module", "Battery Compartment", "Camera Gimbal", "Control Circuit", "Landing Gear"],
    "gamepad": ["Joystick Module", "Button Group", "Trigger Key", "Vibration Motor", "PCB Circuit Board", "Handle Shell"],
    "mechanical keyboard": ["Keycap Group", "Switch Module", "PCB Circuit Board", "Metal Bottom Plate", "USB Cable", "Indicator Light Module"],
    "mouse": ["Left/Right Keys", "Scroll Wheel Module", "Optical Sensor", "PCB Circuit Board", "Micro Switch", "Mouse Shell"],
    "car": ["Roof Shell", "Front Windshield", "Dashboard", "Seat Assembly", "Engine Hood", "Chassis Frame", "Wheel Component"],
    "motorcycle": ["Headlight", "Instrument Cluster", "Fuel Tank Shell", "Seat Cushion", "Engine Body", "Exhaust Pipe", "Rear Wheel Component"],
    "bicycle": ["Frame", "Front Fork", "Derailleur", "Brake System", "Chain Group", "Wheel Set", "Handlebar"],
    "train": ["Locomotive", "Carriage Connection", "Passenger Carriage", "Freight Carriage", "Rail System", "Cable Line"],
    "airplane": ["Nose", "Cockpit", "Wing", "Engine", "Fuselage", "Tail Wing", "Landing Gear"],
    "watch": ["Watch Face Panel", "Crown Button", "Screen Module", "Battery Cell", "Movement Component", "Strap Connector", "Rear Cover"],
    "wallet": ["Leather Outer Layer", "Card Slot", "Cash Slot", "Coin Pocket", "Ticket Slot", "Stitching"],
    "backpack": ["Main Storage Layer", "Front Pocket", "Side Pocket", "Shoulder Strap System", "Waterproof Inner Layer", "Zipper Component"],
    "umbrella": ["Canopy Surface", "Rib Structure", "Central Shaft", "Handle", "Open Close Mechanism", "Windproof Design"],
    "luggage": ["PC Hard Shell", "Pull Rod System", "360 Degree Wheel Set", "Code Lock", "Lining Storage", "TSA Lock"],
    "glasses": ["Frame", "Lens", "Nose Pad", "Temple", "Hinge", "Screw"],
    "hat": ["Hat Top", "Brim", "Inner Lining Pad", "Adjust Buckle", "Breathing Hole", "Tag"],
    "shoes": ["Shoe Upper", "Sole", "Insole", "Shoe Lace", "Breathing Hole", "Reinforced Toe"],
    "bicycle helmet": ["Shell", "EPS Buffer Layer", "Liner", "Adjustment System", "Buckle", "Visor"],
    "camera bag": ["Main Storage Layer", "Memory Card Pocket", "Partition Board", "Zipper Pocket", "Shoulder Strap", "Waterproof Outer Layer"],
    "office chair": ["Chair Back", "Seat Cushion", "Gas Lift", "Five Star Base", "Wheel Set", "Armrest"],
    "desk": ["Desktop", "Table Leg", "Drawer", "Cable Hole", "Keyboard Tray", "Bookshelf"],
    "bed": ["Bed Frame", "Mattress", "Headboard", "Footboard", "Mattress Protector", "Pillow"],
    "wardrobe": ["Door Panel", "Shelf", "Drawer", "Cloth Rod", "LED Strip", "Slide Rail"],
    "bookshelf": ["Shelf", "Side Panel", "Back Panel", "Glass Door", "Wood Door", "Handle"],
    "guitar": ["Headstock", "Neck Rod", "Fretboard Panel", "Resonance Box", "Bridge Component", "Sound Hole Device", "Tuning Peg"],
    "piano": ["Piano Keys", "Keyboard Frame", "Hammer", "String", "Soundboard", "Pedal Mechanism", "Wood Frame"],
    "drum set": ["Bass Drum", "Snare Drum", "Floor Tom", "Tom Tom", "Cymbal", "Hardware Group", "Drumstick"],
    "violin": ["Body", "Neck", "Fingerboard", "Bridge", "String", "Chin Rest", "Bow"],
    "saxophone": ["Main Pipe", "Bend", "Bell", "Key System", "Mouthpiece", "Neck Pipe", "Soft Pad"],
    "basketball": ["Rubber Outer Skin", "Nylon Winding", "Inner Bladder", "Valve", "Buffer Pad"],
    "football": ["Leather Outer Skin", "Air Bladder", "Valve", "Stitching", "Buffer Layer"],
    "tennis racket": ["Racket Frame", "Racket Face", "Racket Neck", "Grip", "Shock Pad", "Stringing"],
    "golf club": ["Club Head", "Shaft", "Grip", "Club Face", "Groove", "Center of Gravity"],
    "snowboard": ["Board Body", "Board Edge", "Binding", "Anti-slip Layer", "Elastic Core", "Sidewall"],
    "coffee machine": ["Water Tank", "Pump", "Heater", "Coffee Slot", "Control Panel", "Drip Tray", "Spout"],
    "toaster": ["Heating Coil", "Bread Slot", "Timer", "Bounce Mechanism", "Chassis", "Power Cord"],
    "blender": ["Motor Base", "Blending Cup", "Blade Group", "Sealing Ring", "Control Knob", "Lid"],
    "rice cooker": ["Inner Pot", "Outer Shell", "Heating Plate", "Control Panel", "Steam Hole", "Power Cord", "Rice Scoop"],
    "air fryer": ["Fry Basket", "Heating Tube", "Fan", "Inner Pot", "Control Panel", "Outer Shell", "Power Cord"],
  };

  const lowerObject = object.toLowerCase();
  let names: string[] = [];

  for (const [key, value] of Object.entries(componentNames)) {
    if (lowerObject.includes(key) || key.includes(lowerObject)) {
      names = value;
      break;
    }
  }

  if (names.length === 0) {
    // Fallback generation
    names = Array.from({ length: 8 }, (_, i) => `${object} Component ${i + 1}`);
  }

  return names.slice(0, Math.min(names.length, 8)).map((name, index) => ({
    id: index + 1,
    name,
    description: `${name} - Core component of ${object}`,
    layer: index + 1,
  }));
}

// Generate prompt
export function generateExplosionPrompt(object: string, components: ExplosionComponent[], styleType: "realistic" | "diagram" | "technical"): string {
  const stylePrompts: Record<"realistic" | "diagram" | "technical", string> = {
    realistic: "Hyper-realistic style, professional studio lighting, soft shadow layers, high dynamic range, macro photography texture, ultra high resolution",
    diagram: "Infographic style, pure white background, clean lines, arrow indicators, professional labels, flat design, ultra high resolution",
    technical: "Technical exploded view, engineering drawing style, dimension lines, size annotations, technical terminology, professional CAD drafting standards, ultra high resolution",
  };

  const componentList = components.map(c => c.name).join(", ");

  return `Create a vertical exploded view infographic showing the decomposition of a ${object}. ${componentList} arranged floating from bottom to top, with subtle shadows and indicator lines marking each component. ${stylePrompts[styleType]}, DSLR macro photography style, delicate indicator lines, ultra clear details, ultra high quality, maximum resolution. Large bold English labels for each component name.`;
}
