"use client";

import React, { useState, useEffect } from "react";

type GenerationStatus = "idle" | "generating" | "success" | "error";

interface ExplosionResult {
  id?: string;
  objectName: string;
  components: Component[];
  imageUrl?: string;
  imageBase64?: string;
  prompt?: string;
  style?: "realistic" | "diagram" | "technical";
  aspectRatio?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
}

interface Component {
  id: number;
  name: string;
  description: string;
  layer: number;
}

export default function ExplosionPage() {
  const [objectInput, setObjectInput] = useState("");
  const [customPrompt, setCustomPrompt] = useState("");
  const [numComponents, setNumComponents] = useState(6);
  const [style, setStyle] = useState<"realistic" | "diagram" | "technical">("diagram");
  const [aspectRatio, setAspectRatio] = useState<"1:1" | "16:9" | "4:3" | "3:2">("16:9");
  const [status, setStatus] = useState<GenerationStatus>("idle");
  const [result, setResult] = useState<ExplosionResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedTab, setSelectedTab] = useState<"create" | "gallery">("create");
  const [galleryItems, setGalleryItems] = useState<ExplosionResult[]>([]);
  const [autoGalleryItems, setAutoGalleryItems] = useState<ExplosionResult[]>([]);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [generatedImages, setGeneratedImages] = useState<{angleId: string; angleName: string; url: string}[]>([]);
  const [selectedAngles, setSelectedAngles] = useState<string[]>(["side", "three-quarter"]);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const [galleryStats, setGalleryStats] = useState<{totalGenerated: number; lastCronRun: string | null} | null>(null);
  const [analysisSource, setAnalysisSource] = useState<string>("");
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [previewImage, setPreviewImage] = useState<{url: string; name: string} | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const [autoAnalyze, setAutoAnalyze] = useState(false); // 是否自動分析

  const sourceLabels: Record<string, string> = {
    domain_db: "📚 專業資料庫",
    wikipedia: "🌐 Wikipedia",
    ai: "🤖 AI 分析",
    fallback: "⚠️ 萬用生成",
  };

  // 讀取從 Prompt 庫選擇的 prompt
  useEffect(() => {
    const stored = sessionStorage.getItem("selectedPrompt");
    if (stored) {
      try {
        const promptData = JSON.parse(stored);
        if (promptData.category === "explosion") {
          // 爆炸圖 Prompt - 設置物件名稱並分析
          let objectName = promptData.title || "";
          objectName = objectName.replace(/爆炸圖|寫實風格|資訊圖表|技術製圖|3D\s*等軸測|海報設計|童書插畫/g, "").trim();
          if (objectName) {
            setObjectInput(objectName);
            setAutoAnalyze(true);
          }
        } else if (promptData.category === "image" && promptData.prompt) {
          // 圖像 Prompt - 保存到 customPrompt 並顯示提示
          setCustomPrompt(promptData.prompt || "");
        }
      } catch {
        // ignore
      }
      sessionStorage.removeItem("selectedPrompt");
    }
  }, []);

  // 自動分析（當從 Prompt 庫傳來爆炸圖 prompt 時）
  useEffect(() => {
    if (autoAnalyze && objectInput && status === "idle") {
      const timer = setTimeout(() => {
        if (objectInput.trim()) {
          // 直接調用分析
          setError(null);
          setStatus("generating");
          setIsAnalyzing(true);

          fetch(`/api/analyze-object?object=${encodeURIComponent(objectInput)}&count=${numComponents}&style=${style}&aspectRatio=${aspectRatio}`)
            .then(res => res.json())
            .then(data => {
              if (data.error) {
                setError(data.error);
                setStatus("error");
                return;
              }
              const analysisData = data.data;
              setAnalysisSource(sourceLabels[analysisData.source] || analysisData.source);
              setResult({
                objectName: analysisData.objectName,
                components: analysisData.components,
                prompt: analysisData.prompt,
              });
              setStatus("success");
            })
            .catch(() => {
              setError("分析失敗，請稍後重試");
              setStatus("error");
            })
            .finally(() => {
              setIsAnalyzing(false);
            });
        }
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [autoAnalyze, objectInput, status]);

  // Camera angles for multi-view generation
  const CAMERA_ANGLES = [
    { id: "front", name: "正面", suffix: "from the front view, straight-on perspective" },
    { id: "side", name: "側面", suffix: "from the side view, 90-degree angle" },
    { id: "top", name: "頂部", suffix: "from the top-down overhead perspective" },
    { id: "isometric", name: "等軸測", suffix: "isometric 3D perspective, 30-degree angles" },
    { id: "three-quarter", name: "三分視角", suffix: "three-quarter view, showing front and side" },
  ];

  const toggleAngle = (angleId: string) => {
    setSelectedAngles(prev => {
      if (prev.includes(angleId)) {
        if (prev.length <= 1) return prev; // Keep at least one
        return prev.filter(id => id !== angleId);
      } else {
        if (prev.length >= 2) return [...prev.slice(1), angleId]; // Max 2
        return [...prev, angleId];
      }
    });
  };

  // Load gallery from localStorage and server
  useEffect(() => {
    // Load user gallery from localStorage
    const stored = localStorage.getItem("explosion_gallery");
    if (stored) {
      try {
        setGalleryItems(JSON.parse(stored));
      } catch {
        setGalleryItems([]);
      }
    }

    // Load auto-generated gallery from server
    fetch("/api/explosion-gallery")
      .then((res) => res.json())
      .then((data) => {
        if (data.success && data.data) {
          setAutoGalleryItems(data.data);
          if (data.index) {
            setGalleryStats({
              totalGenerated: data.index.totalGenerated,
              lastCronRun: data.index.lastCronRun,
            });
          }
        }
      })
      .catch((err) => {
        console.error("載入自動圖庫失敗:", err);
      });
  }, []);

  // Save gallery to localStorage (with size limit)
  const saveGallery = (items: ExplosionResult[]) => {
    setGalleryItems(items);
    try {
      // Keep only last 50 items to avoid quota exceeded
      const limitedItems = items.slice(0, 50);
      localStorage.setItem("explosion_gallery", JSON.stringify(limitedItems));
    } catch (err) {
      console.error("保存圖庫失敗:", err);
      // If still fails, clear old data and retry with just last 20
      const minimalItems = items.slice(0, 20);
      try {
        localStorage.setItem("explosion_gallery", JSON.stringify(minimalItems));
      } catch {
        // Clear completely if even that fails
        localStorage.removeItem("explosion_gallery");
      }
    }
  };

  // Analyze object and generate explosion components
  const analyzeObject = async () => {
    if (!objectInput.trim()) {
      setError("請輸入要分析的物件");
      return;
    }

    setError(null);
    setStatus("generating");
    setGeneratedImage(null);
    setIsAnalyzing(true);

    try {
      const response = await fetch(
        `/api/analyze-object?object=${encodeURIComponent(objectInput)}&count=${numComponents}&style=${style}&aspectRatio=${aspectRatio}`
      );

      const data = await response.json();

      if (data.error) {
        setError(data.error);
        setStatus("error");
        return;
      }

      const analysisData = data.data;

      setAnalysisSource(sourceLabels[analysisData.source] || analysisData.source);

      setResult({
        objectName: analysisData.objectName,
        components: analysisData.components,
        prompt: analysisData.prompt,
      });
      setStatus("success");
    } catch (err) {
      setError("分析失敗，請稍後重試");
      setStatus("error");
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Generate explosion diagram image using MiniMax API
  const generateDiagram = async () => {
    if (!result) return;

    setIsGeneratingImage(true);
    setStatus("generating");
    setGeneratedImages([]);

    try {
      // 優先使用自訂 prompt，其次使用分析出來的 prompt
      const promptToUse = customPrompt || result.prompt;

      const response = await fetch("/api/minimax/image", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          prompt: promptToUse,
          aspect_ratio: aspectRatio,
          angles: selectedAngles,
        }),
      });

      const data = await response.json();

      if (data.error) {
        setError(data.error);
        setStatus("error");
        setIsGeneratingImage(false);
        return;
      }

      if (data.images && Array.isArray(data.images)) {
        const imagesWithUrls = data.images.map((img: {angleId: string; angleName: string; image_base64: string}) => ({
          angleId: img.angleId,
          angleName: img.angleName,
          url: `data:image/jpeg;base64,${img.image_base64}`,
        }));
        setGeneratedImages(imagesWithUrls);
        setGeneratedImage(imagesWithUrls[0]?.url || null);

        const updatedResult = {
          ...result,
          imageUrl: imagesWithUrls[0]?.url,
          imageBase64: data.images[0]?.image_base64,
          style,
          aspectRatio,
        };
        setResult(updatedResult);
        setStatus("success");

        // 自動添加到圖庫（只存第一張）
        const galleryItem: ExplosionResult = {
          id: `gallery-${Date.now()}`,
          objectName: result.objectName,
          components: result.components,
          imageUrl: imagesWithUrls[0]?.url,
          imageBase64: data.images[0]?.image_base64,
          prompt: result.prompt,
          style,
          aspectRatio,
          createdAt: new Date().toISOString(),
          isAutoGenerated: false,
        };
        const newGallery = [galleryItem, ...galleryItems];
        saveGallery(newGallery);
        setToast(`已自動添加到圖庫：${result.objectName}`);
        setTimeout(() => setToast(null), 3000);
      } else {
        setError("圖片生成失敗，請稍後重試");
        setStatus("error");
      }
    } catch (err) {
      console.error("圖片生成失敗:", err);
      setError("圖片生成失敗，請檢查網絡連接");
      setStatus("error");
    } finally {
      setIsGeneratingImage(false);
    }
  };

  // Fallback direct image generation (for image prompts from library)
  const generateDirectImage = async () => {
    if (!customPrompt || !objectInput.trim()) {
      setError("請輸入物件名稱");
      return;
    }

    setIsGeneratingImage(true);
    setStatus("generating");
    setGeneratedImages([]);

    try {
      const fullPrompt = `${customPrompt}, ${objectInput}`;
      const response = await fetch("/api/minimax/image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: fullPrompt,
          aspect_ratio: aspectRatio,
          angles: selectedAngles,
        }),
      });

      const data = await response.json();
      console.log("[DirectImage] API Response:", data);

      if (data.error) {
        setError(data.error);
        setStatus("error");
        setIsGeneratingImage(false);
        return;
      }

      if (data.images && Array.isArray(data.images)) {
        const imagesWithUrls = data.images.map((img: {angleId: string; angleName: string; image_base64: string}) => ({
          angleId: img.angleId,
          angleName: img.angleName,
          url: `data:image/jpeg;base64,${img.image_base64}`,
        }));
        setGeneratedImages(imagesWithUrls);
        setGeneratedImage(imagesWithUrls[0]?.url || null);
        setStatus("success");
      } else {
        setError("圖片生成失敗，請稍後重試");
        setStatus("error");
      }
    } catch (err) {
      console.error("[DirectImage] Error:", err);
      setError("圖片生成失敗，請檢查網絡連接");
      setStatus("error");
    } finally {
      setIsGeneratingImage(false);
    }
  };

  // Add to gallery
  const addToGallery = () => {
    if (result) {
      const newGallery = [result, ...galleryItems];
      saveGallery(newGallery);
    }
  };

  // Delete from gallery
  const deleteFromGallery = (index: number) => {
    if (!confirm("確定要刪除這個作品嗎？")) return;
    const newGallery = galleryItems.filter((_, i) => i !== index);
    saveGallery(newGallery);
  };

  // Drag and drop reorder
  const handleDragStart = (index: number) => {
    setDraggedIndex(index);
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    setDragOverIndex(index);
  };

  const handleDragEnd = () => {
    if (draggedIndex !== null && dragOverIndex !== null && draggedIndex !== dragOverIndex) {
      const newGallery = [...galleryItems];
      const [draggedItem] = newGallery.splice(draggedIndex, 1);
      newGallery.splice(dragOverIndex, 0, draggedItem);
      saveGallery(newGallery);
    }
    setDraggedIndex(null);
    setDragOverIndex(null);
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100">
          爆炸圖生成器
        </h1>
        <p className="mt-1 text-sm text-neutral-600 dark:text-neutral-400">
          將任何物件拆解成詳細的爆炸示意圖
        </p>
      </div>

      {/* Tabs */}
      <div className="mb-6 flex gap-2 border-b border-neutral-200 dark:border-neutral-700">
        <button
          onClick={() => setSelectedTab("create")}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            selectedTab === "create"
              ? "border-b-2 border-[#2563EB] text-[#2563EB]"
              : "text-neutral-600 hover:text-neutral-900 dark:text-neutral-400"
          }`}
        >
          建立爆炸圖
        </button>
        <button
          onClick={() => setSelectedTab("gallery")}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            selectedTab === "gallery"
              ? "border-b-2 border-[#2563EB] text-[#2563EB]"
              : "text-neutral-600 hover:text-neutral-900 dark:text-neutral-400"
          }`}
        >
          我的作品 ({galleryItems.length})
        </button>
      </div>

      {/* Create Tab */}
      {selectedTab === "create" && (
        <div className="flex flex-col h-[calc(100vh-200px)] min-h-[600px]">
          {/* Quick Select Bar */}
          <div className="mb-4 p-4 rounded-xl border border-neutral-200 bg-gradient-to-r from-[#2563EB]/5 to-[#10B981]/5 dark:border-neutral-700">
            <div className="flex items-center justify-between mb-3">
              <span className="text-sm font-medium text-neutral-600 dark:text-neutral-300">🔥 熱門物件</span>
              <span className="text-xs text-neutral-400">點擊即可快速分析</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {["智慧手機", "筆記型電腦", "相機", "耳機", "無人機", "汽車", "摩托車", "吉他", "咖啡機", "機械鍵盤"].map((item) => (
                <button
                  key={item}
                  onClick={() => {
                    setObjectInput(item);
                    setStatus("idle");
                    setResult(null);
                    setGeneratedImage(null);
                  }}
                  className="rounded-full border border-[#2563EB]/30 bg-white px-4 py-2 text-sm font-medium text-[#2563EB] transition-all hover:border-[#2563EB] hover:bg-[#2563EB]/10 hover:shadow-md dark:bg-neutral-800"
                >
                  {item}
                </button>
              ))}
            </div>
          </div>

          {/* Top Control Bar */}
          <div className="flex flex-wrap items-center gap-4 mb-4 p-4 rounded-xl border border-neutral-200 bg-white dark:border-neutral-700 dark:bg-neutral-800">
            {/* Object Input */}
            <div className="flex-1 min-w-[200px]">
              <input
                type="text"
                value={objectInput}
                onChange={(e) => setObjectInput(e.target.value)}
              placeholder={customPrompt ? "已套用 Prompt 模板，輸入物件名稱..." : "或輸入自訂物件名稱..."}
                className="w-full rounded-lg border border-neutral-300 px-4 py-2 text-sm focus:border-[#2563EB] focus:outline-none dark:border-neutral-600 dark:bg-neutral-700 dark:text-neutral-100"
              />
              {customPrompt && (
                <p className="mt-1 text-xs text-[#10B981]">
                  ✨ 已套用 Prompt 模板：{customPrompt.length > 80 ? customPrompt.substring(0, 80) + "..." : customPrompt}
                </p>
              )}
            </div>

            {/* Number of Components */}
            <div className="flex items-center gap-2">
              <span className="text-sm text-neutral-600 dark:text-neutral-300">組件:</span>
              <select
                value={numComponents}
                onChange={(e) => setNumComponents(parseInt(e.target.value))}
                className="rounded-lg border border-neutral-300 px-2 py-1 text-sm dark:border-neutral-600 dark:bg-neutral-700"
              >
                {[3, 4, 5, 6, 7, 8].map(n => (
                  <option key={n} value={n}>{n}</option>
                ))}
              </select>
            </div>

            {/* Style Selection */}
            <div className="flex gap-1">
              {(["realistic", "diagram", "technical"] as const).map((s) => (
                <button
                  key={s}
                  onClick={() => setStyle(s)}
                  className={`rounded-lg px-3 py-1 text-sm font-medium transition-colors ${
                    style === s
                      ? s === "technical"
                        ? "bg-[#2563EB] text-white"
                        : "bg-[#10B981] text-white"
                      : "bg-neutral-100 text-neutral-600 dark:bg-neutral-700 dark:text-neutral-300"
                  }`}
                >
                  {s === "realistic" ? "寫實" : s === "diagram" ? "訊息圖" : "技術圖"}
                </button>
              ))}
            </div>

            {/* Aspect Ratio */}
            <div className="flex gap-1">
              {(["1:1", "16:9", "4:3", "3:2"] as const).map((ratio) => (
                <button
                  key={ratio}
                  onClick={() => setAspectRatio(ratio)}
                  className={`rounded-lg px-2 py-1 text-xs font-medium ${
                    aspectRatio === ratio
                      ? "bg-[#2563EB] text-white"
                      : "bg-neutral-100 text-neutral-600 dark:bg-neutral-700 dark:text-neutral-300"
                  }`}
                >
                  {ratio}
                </button>
              ))}
            </div>

            {/* Camera Angle Selection */}
            <div className="flex items-center gap-2">
              <span className="text-sm text-neutral-600 dark:text-neutral-300">視角：</span>
              <div className="flex gap-1 flex-wrap">
                {CAMERA_ANGLES.map((angle) => (
                  <button
                    key={angle.id}
                    onClick={() => toggleAngle(angle.id)}
                    className={`rounded-lg px-2 py-1 text-xs font-medium transition-colors ${
                      selectedAngles.includes(angle.id)
                        ? "bg-[#10B981] text-white"
                        : "bg-neutral-100 text-neutral-600 dark:bg-neutral-700 dark:text-neutral-300"
                    }`}
                  >
                    {angle.name}
                  </button>
                ))}
              </div>
              <span className="text-xs text-neutral-400">({selectedAngles.length}/2)</span>
            </div>

            {/* Analyze Button */}
            <button
              onClick={analyzeObject}
              disabled={status === "generating" || isAnalyzing}
              className="rounded-lg bg-[#2563EB] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[#1D4ED8] disabled:opacity-50"
            >
              {isAnalyzing ? "分析中..." : "分析"}
            </button>

            {/* Direct Generate Button (for image prompts from library) */}
            {customPrompt && !result && (
              <button
                onClick={generateDirectImage}
                disabled={!objectInput.trim() || isGeneratingImage}
                className="rounded-lg bg-[#10B981] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[#059669] disabled:opacity-50"
              >
                {isGeneratingImage ? "生成中..." : "✨ 直接生成"}
              </button>
            )}
          </div>

          {/* Component List - Horizontal Scroll */}
          {status === "success" && result && (
            <div className="mb-4 p-4 rounded-xl border border-neutral-200 bg-white dark:border-neutral-700 dark:bg-neutral-800">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-4">
                  <h2 className="text-lg font-semibold text-neutral-900 dark:text-neutral-100">
                    {result.objectName}
                  </h2>
                  {analysisSource && (
                    <span className="rounded-full bg-[#2563EB]/10 px-2 py-0.5 text-xs text-[#2563EB]">
                      {analysisSource}
                    </span>
                  )}
                </div>
                <div className="flex gap-2">
                  <button
                    onClick={generateDiagram}
                    disabled={isGeneratingImage}
                    className="rounded-lg bg-[#10B981] px-4 py-1.5 text-sm font-medium text-white hover:bg-[#059669] disabled:opacity-50"
                  >
                    {isGeneratingImage ? "生成中..." : "生成圖片"}
                  </button>
                  <button
                    onClick={addToGallery}
                    className="rounded-lg border border-neutral-300 px-3 py-1.5 text-sm text-neutral-700 hover:bg-neutral-100 dark:border-neutral-600 dark:text-neutral-200"
                  >
                    收藏
                  </button>
                </div>
              </div>

              {/* Horizontal Component List */}
              <div className="flex gap-4 overflow-x-auto pb-2">
                {result.components.map((component) => (
                  <div
                    key={component.id}
                    className="flex-shrink-0 w-56 rounded-xl border-2 border-[#2563EB]/30 bg-gradient-to-b from-white to-neutral-50 p-4 dark:border-neutral-700 dark:from-neutral-800 dark:to-neutral-900"
                  >
                    <div className="flex items-center gap-3 mb-3">
                      <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#2563EB] text-lg font-bold text-white shadow-md">
                        {component.layer}
                      </div>
                      <span className="text-sm font-medium text-neutral-400">第 {component.layer} 層</span>
                    </div>
                    <p className="text-lg font-bold text-neutral-900 dark:text-neutral-100 mb-1">
                      {component.name}
                    </p>
                    <p className="text-sm text-neutral-600 dark:text-neutral-400 leading-relaxed">
                      {component.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Full-Width Image Preview Area - Bottom Half */}
          <div className="flex-1 min-h-[400px] rounded-xl border-2 border-dashed border-neutral-300 bg-neutral-50 dark:border-neutral-700 dark:bg-neutral-900 overflow-hidden">
            {/* Generating State */}
            {status === "generating" && isGeneratingImage && (
              <div className="flex flex-col items-center justify-center h-full">
                <div className="mb-4 h-16 w-16 animate-spin rounded-full border-4 border-[#10B981] border-t-transparent"></div>
                <p className="text-neutral-500">MiniMax 圖像生成中，請稍候...</p>
                <p className="mt-1 text-xs text-neutral-400">
                  {aspectRatio === "1:1" ? "2048×2048" : aspectRatio === "16:9" ? "2048×1152" : aspectRatio === "4:3" ? "2048×1536" : "2048×1365"} pixels
                </p>
              </div>
            )}

            {/* Analyzing State */}
            {status === "generating" && isAnalyzing && (
              <div className="flex flex-col items-center justify-center h-full">
                <div className="mb-4 h-16 w-16 animate-spin rounded-full border-4 border-[#2563EB] border-t-transparent"></div>
                <p className="text-neutral-500">正在使用知識圖譜分析物件結構...</p>
                <p className="mt-1 text-xs text-neutral-400">專業資料庫 → Wikipedia → AI 分析</p>
              </div>
            )}

            {/* Idle State - Show placeholder */}
            {status === "idle" && !result && (
              <div className="flex flex-col items-center justify-center h-full">
                <div className="mb-4 text-8xl text-neutral-300">💥</div>
                {customPrompt ? (
                  <>
                    <p className="text-xl text-neutral-400">已套用 Prompt 模板</p>
                    <p className="mt-2 text-sm text-neutral-400">輸入物件名稱，點擊「直接生成」</p>
                  </>
                ) : (
                  <>
                    <p className="text-xl text-neutral-400">輸入物件名稱開始分析</p>
                    <p className="mt-2 text-sm text-neutral-400">
                      爆炸圖將以 {aspectRatio === "1:1" ? "2048×2048" : aspectRatio === "16:9" ? "2048×1152" : aspectRatio === "4:3" ? "2048×1536" : "2048×1365"} 解析度呈現
                    </p>
                  </>
                )}
              </div>
            )}

            {/* Error State */}
            {error && (
              <div className="flex flex-col items-center justify-center h-full">
                <div className="mb-4 text-6xl text-red-300">⚠️</div>
                <p className="text-red-500">{error}</p>
              </div>
            )}

            {/* Success with Image(s) */}
            {status === "success" && (generatedImage || generatedImages.length > 0) && (
              <div className="w-full h-full bg-black/5 dark:bg-white/5 overflow-auto">
                {/* Multi-view grid */}
                <div className="flex gap-2 p-4 h-full">
                  {generatedImages.map((img, index) => (
                    <div key={img.angleId} className="flex-1 min-w-0 relative group">
                      <img
                        src={img.url}
                        alt={`${result?.objectName} - ${img.angleName}`}
                        className="w-full h-full object-contain rounded-lg"
                      />
                      {/* Angle label */}
                      <div className="absolute top-2 left-2 bg-black/60 text-white text-xs px-2 py-1 rounded">
                        {img.angleName}
                      </div>
                      {/* Download button */}
                      <a
                        href={img.url}
                        download={`explosion-${result?.objectName}-${img.angleId}-${Date.now()}.jpg`}
                        className="absolute bottom-2 right-2 bg-[#2563EB] text-white text-xs px-3 py-1.5 rounded opacity-0 group-hover:opacity-100 transition-opacity"
                      >
                        下載
                      </a>
                    </div>
                  ))}
                </div>
                {/* Image Actions */}
                <div className="absolute bottom-4 right-4 flex gap-2">
                  <button
                    onClick={generateDiagram}
                    disabled={isGeneratingImage}
                    className="rounded-lg bg-white/90 px-4 py-2 text-sm font-medium text-neutral-700 hover:bg-white shadow-lg dark:bg-neutral-800/90 dark:text-neutral-200"
                  >
                    重新生成
                  </button>
                </div>
              </div>
            )}

            {/* Success without Image yet */}
            {status === "success" && result && !generatedImage && !isGeneratingImage && (
              <div className="flex flex-col items-center justify-center h-full">
                <div className="mb-4 text-6xl text-neutral-300">🖼️</div>
                <p className="text-neutral-500">點擊「生成圖片」開始製作爆炸圖</p>
                <p className="mt-1 text-xs text-neutral-400">
                  解析度：{aspectRatio === "1:1" ? "2048×2048" : aspectRatio === "16:9" ? "2048×1152" : aspectRatio === "4:3" ? "2048×1536" : "2048×1365"} pixels
                </p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Gallery Tab */}
      {selectedTab === "gallery" && (
        <div>
          {/* Stats Bar */}
          <div className="mb-6 rounded-xl border border-neutral-200 bg-gradient-to-r from-[#2563EB]/10 to-[#10B981]/10 p-4 dark:border-neutral-700 dark:from-[#2563EB]/5 dark:to-[#10B981]/5">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <div className="flex flex-wrap gap-6">
                <div>
                  <p className="text-sm text-neutral-500">自動生成</p>
                  <p className="text-2xl font-bold text-[#2563EB]">{autoGalleryItems.length}</p>
                </div>
                <div>
                  <p className="text-sm text-neutral-500">我的收藏</p>
                  <p className="text-2xl font-bold text-[#10B981]">{galleryItems.length}</p>
                </div>
                {galleryStats?.lastCronRun && (
                  <div>
                    <p className="text-sm text-neutral-500">上次自動生成</p>
                    <p className="text-sm font-medium text-neutral-700 dark:text-neutral-300">
                      {new Date(galleryStats.lastCronRun).toLocaleString("zh-TW")}
                    </p>
                  </div>
                )}
              </div>
              <div className="flex gap-2">
                <button
                  onClick={async () => {
                    if (!confirm("確定要手動觸發自動生成任務嗎？")) return;
                    try {
                      const res = await fetch("/api/explosion-cron?force=true");
                      const data = await res.json();
                      alert(data.message || `完成: ${data.successCount} 組`);
                      // 重新載入
                      window.location.reload();
                    } catch {
                      alert("觸發失敗");
                    }
                  }}
                  className="rounded-lg bg-[#2563EB] px-4 py-2 text-sm font-medium text-white hover:bg-[#1D4ED8]"
                >
                  立即生成 40 組
                </button>
                <button
                  onClick={async () => {
                    // 重新整理
                    window.location.reload();
                  }}
                  className="rounded-lg border border-neutral-300 px-4 py-2 text-sm font-medium text-neutral-700 hover:bg-neutral-100 dark:border-neutral-600 dark:text-neutral-200"
                >
                  重新整理
                </button>
              </div>
            </div>
          </div>

          {/* Auto-Generated Gallery */}
          {autoGalleryItems.length > 0 && (
            <div className="mb-8">
              <h2 className="mb-4 text-lg font-semibold text-neutral-900 dark:text-neutral-100 flex items-center gap-2">
                <span className="text-xl">🤖</span> 自動生成圖庫
              </h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
                {autoGalleryItems.map((item, index) => (
                  <div
                    key={item.id || `auto-${index}`}
                    className="rounded-xl border-2 border-[#2563EB]/30 bg-white p-3 transition-all dark:border-[#2563EB]/30 dark:bg-neutral-800"
                  >
                    {item.imageUrl && (
                      <div
                        className="mb-2 overflow-hidden rounded-lg cursor-pointer hover:opacity-90 transition-opacity"
                        onClick={() => setPreviewImage({ url: item.imageUrl!, name: item.objectName })}
                      >
                        <img
                          src={item.imageUrl}
                          alt={item.objectName}
                          className="h-28 w-full object-cover"
                        />
                      </div>
                    )}
                    <div className="flex items-center justify-between mb-1">
                      <div className="flex items-center gap-2">
                        <span className="rounded-full bg-[#2563EB]/10 px-2 py-0.5 text-xs text-[#2563EB]">
                          {item.style === "realistic" ? "寫實" : item.style === "diagram" ? "訊息圖" : "技術圖"}
                        </span>
                        <span className="text-xs text-neutral-500">{item.aspectRatio}</span>
                      </div>
                      {item.imageUrl && (
                        <a
                          href={item.imageUrl}
                          download={`explosion-${item.objectName}-${Date.now()}.jpg`}
                          className="rounded-lg px-2 py-0.5 text-sm text-[#10B981] hover:bg-[#10B981]/10"
                          title="下載"
                        >
                          ⬇️
                        </a>
                      )}
                    </div>
                    <h3 className="mt-1 font-bold text-neutral-900 dark:text-neutral-100">
                      {item.objectName}
                    </h3>
                    <p className="text-xs text-neutral-500">{item.components.length} 個組件</p>
                    <button
                      onClick={() => {
                        const newItem = { ...item, id: `user-${Date.now()}`, isAutoGenerated: true };
                        const newGallery = [newItem, ...galleryItems];
                        saveGallery(newGallery);
                        setToast(`已添加到我的收藏：${item.objectName}`);
                        setTimeout(() => setToast(null), 3000);
                      }}
                      className="mt-2 w-full rounded-lg bg-[#10B981] px-3 py-1 text-xs font-medium text-white hover:bg-[#059669]"
                    >
                      收藏
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* User Gallery */}
          {galleryItems.length > 0 && (
            <div>
              <h2 className="mb-4 text-lg font-semibold text-neutral-900 dark:text-neutral-100 flex items-center gap-2">
                <span className="text-xl">👤</span> 我的收藏
                <span className="text-sm font-normal text-neutral-500">（拖曳可排序）</span>
              </h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {galleryItems.map((item, index) => (
                  <div
                    key={index}
                    draggable
                    onDragStart={() => handleDragStart(index)}
                    onDragOver={(e) => handleDragOver(e, index)}
                    onDragEnd={handleDragEnd}
                    className={`rounded-xl border-2 bg-white p-4 transition-all cursor-grab active:cursor-grabbing ${
                      dragOverIndex === index
                        ? "border-[#10B981] shadow-lg scale-[1.02]"
                        : "border-neutral-200 dark:border-neutral-700 hover:border-neutral-300 dark:hover:border-neutral-600"
                    } ${
                      draggedIndex === index ? "opacity-50" : "opacity-100"
                    }`}
                  >
                    {/* Drag Handle & Actions */}
                    <div className="mb-2 flex items-center justify-between">
                      <div className="flex items-center gap-2 text-neutral-400">
                        <span className="text-lg">☰</span>
                        <span className="text-xs">拖曳排序</span>
                      </div>
                      <div className="flex items-center gap-1">
                        {item.imageUrl && (
                          <>
                            <button
                              onClick={() => setPreviewImage({ url: item.imageUrl!, name: item.objectName })}
                              className="rounded-lg px-2 py-1 text-sm text-[#2563EB] hover:bg-[#2563EB]/10"
                              title="預覽"
                            >
                              🔍
                            </button>
                            <a
                              href={item.imageUrl}
                              download={`explosion-${item.objectName}-${Date.now()}.jpg`}
                              className="rounded-lg px-2 py-1 text-sm text-[#10B981] hover:bg-[#10B981]/10"
                              title="下載"
                            >
                              ⬇️
                            </a>
                          </>
                        )}
                        <button
                          onClick={() => deleteFromGallery(index)}
                          className="rounded-lg px-2 py-1 text-sm text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20"
                          title="刪除"
                        >
                          ✕
                        </button>
                      </div>
                    </div>

                    {item.imageUrl && (
                      <div
                        className="mb-3 overflow-hidden rounded-lg cursor-pointer hover:opacity-90 transition-opacity"
                        onClick={() => setPreviewImage({ url: item.imageUrl!, name: item.objectName })}
                      >
                        <img
                          src={item.imageUrl}
                          alt={item.objectName}
                          className="h-40 w-full object-cover"
                        />
                      </div>
                    )}
                    <div className="flex items-center gap-2 mb-1">
                      <span className="rounded-full bg-[#10B981]/10 px-2 py-0.5 text-xs text-[#10B981]">
                        {item.style === "realistic" ? "寫實" : item.style === "diagram" ? "訊息圖" : "技術圖"}
                      </span>
                      <span className="text-xs text-neutral-500">{item.aspectRatio}</span>
                    </div>
                    <h3 className="text-lg font-bold text-neutral-900 dark:text-neutral-100">
                      {item.objectName}
                    </h3>
                    <p className="mt-1 text-sm text-neutral-500">
                      {item.components.length} 個組件
                    </p>
                    <div className="mt-2 flex flex-wrap gap-1">
                      {item.components.slice(0, 4).map((c) => (
                        <span
                          key={c.id}
                          className="rounded-full bg-neutral-100 px-2 py-0.5 text-xs dark:bg-neutral-700"
                        >
                          {c.name}
                        </span>
                      ))}
                      {item.components.length > 4 && (
                        <span className="text-xs text-neutral-500">
                          +{item.components.length - 4}
                        </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Empty State */}
          {galleryItems.length === 0 && autoGalleryItems.length === 0 && (
            <div className="flex h-64 flex-col items-center justify-center rounded-xl border border-neutral-200 border-dashed bg-neutral-50 dark:border-neutral-700 dark:bg-neutral-900">
              <div className="mb-4 text-6xl text-neutral-300">🖼️</div>
              <p className="text-neutral-500">暫無收藏作品</p>
              <p className="mt-1 text-sm text-neutral-400">點擊「立即生成 40 組」開始自動建立圖庫</p>
            </div>
          )}
        </div>
      )}

      {/* Image Preview Modal */}
      {previewImage && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"
          onClick={() => setPreviewImage(null)}
        >
          <div className="relative max-w-4xl w-full">
            <button
              onClick={() => setPreviewImage(null)}
              className="absolute -top-10 right-0 text-white text-2xl hover:text-gray-300"
            >
              ✕
            </button>
            <img
              src={previewImage.url}
              alt={previewImage.name}
              className="w-full rounded-lg"
            />
            <p className="mt-2 text-center text-white text-lg font-medium">
              {previewImage.name}
            </p>
          </div>
        </div>
      )}

      {/* Toast Notification */}
      {toast && (
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 rounded-lg bg-[#10B981] px-6 py-3 text-white shadow-lg flex items-center gap-2 animate-fade-in">
          <span className="text-lg">✓</span>
          <span className="font-medium">{toast}</span>
        </div>
      )}
    </div>
  );
}
