import { NextRequest, NextResponse } from "next/server";
import {
  loadExplosionIndex,
  saveExplosionIndex,
  loadExplosionGallery,
  saveExplosionGallery,
  getPendingObjects,
  markObjectAsGenerated,
  updateLastCronRun,
  shouldRunCron,
  generateComponentsForObject,
  generateExplosionPrompt,
  ExplosionResult,
  EXPLOSION_GALLERY_FILE,
} from "@/lib/explosion-store";
import fs from "fs";
import path from "path";

const API_BASE = "https://api.minimax.io";

/**
 * 爆炸圖 Cron 任務
 * 每 20 小時自動生成 40 組爆炸圖
 * 執行方式：GET /api/explosion-cron
 * 或由外部 Cron 服務觸發
 */

// 安全的檔案路徑
function getGalleryPath() {
  const DATA_DIR = path.join(process.cwd(), ".data");
  return path.join(DATA_DIR, "explosion-gallery.json");
}

// 生成單一爆炸圖
async function generateSingleExplosion(
  objectName: string,
  style: "realistic" | "diagram" | "technical",
  aspectRatio: string
): Promise<ExplosionResult | null> {
  try {
    // 生成組件
    const components = generateComponentsForObject(objectName, 6);
    // 生成提示詞
    const prompt = generateExplosionPrompt(objectName, components, style);

    // 調用 MiniMax API
    const API_KEY = process.env.MINIMAX_API_KEY;
    if (!API_KEY) {
      console.error("[ExplosionCron] MINIMAX_API_KEY not set");
      return null;
    }

    const response = await fetch(`${API_BASE}/v1/image_generation`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "image-01",
        prompt,
        aspect_ratio: aspectRatio,
        response_format: "base64",
      }),
    });

    if (!response.ok) {
      console.error(`[ExplosionCron] API error for ${objectName}:`, response.status);
      return null;
    }

    const data = await response.json();

    // 檢查 API 回應錯誤
    if (data.base_resp && data.base_resp.status_code !== 0) {
      console.error(`[ExplosionCron] API status error for ${objectName}:`, data.base_resp.status_msg);
      return null;
    }

    if (!data.data || !data.data.image_base64 || !Array.isArray(data.data.image_base64) || data.data.image_base64.length === 0) {
      console.error(`[ExplosionCron] No image data for ${objectName}`);
      return null;
    }

    const imageBase64 = data.data.image_base64[0];
    const imageUrl = `data:image/jpeg;base64,${imageBase64}`;

    const result: ExplosionResult = {
      id: `EXPL-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      objectName,
      components,
      imageUrl,
      imageBase64,
      prompt,
      style,
      aspectRatio,
      createdAt: new Date().toISOString(),
      isAutoGenerated: true,
    };

    return result;
  } catch (error) {
    console.error(`[ExplosionCron] Error generating ${objectName}:`, error);
    return null;
  }
}

// 風格陣列
const STYLES: Array<"realistic" | "diagram" | "technical"> = ["realistic", "diagram", "technical"];
const ASPECT_RATIOS = ["1:1", "16:9", "4:3", "3:2"];

// GET - 執行 Cron 任務
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const force = searchParams.get("force") === "true"; // 強制執行
  const secret = searchParams.get("secret");

  // 簡單的授權檢查（可以設置複雜的密鑰）
  const CRON_SECRET = process.env.CRON_SECRET;
  if (CRON_SECRET && secret !== CRON_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // 檢查是否應該執行
  if (!force && !shouldRunCron()) {
    const index = loadExplosionIndex();
    const lastRun = index.lastCronRun ? new Date(index.lastCronRun) : null;
    const nextRun = lastRun ? new Date(lastRun.getTime() + 20 * 60 * 60 * 1000) : null;

    return NextResponse.json({
      status: "skipped",
      message: "距離上次執行未滿 20 小時",
      lastRun: index.lastCronRun,
      nextRun: nextRun?.toISOString() || "立即可執行",
      totalGenerated: index.totalGenerated,
      pendingObjects: getPendingObjects().length,
    });
  }

  console.log("[ExplosionCron] 開始執行爆炸圖生成任務...");

  // 取得待生成物件
  const pendingObjects = getPendingObjects(40);

  if (pendingObjects.length === 0) {
    updateLastCronRun();
    return NextResponse.json({
      status: "completed",
      message: "所有物件都已生成完畢",
      totalGenerated: loadExplosionIndex().totalGenerated,
    });
  }

  console.log(`[ExplosionCron] 待生成物件: ${pendingObjects.length} 個`);

  // 載入現有圖庫
  const gallery = loadExplosionGallery();
  let successCount = 0;
  let failCount = 0;
  const errors: string[] = [];

  // 逐一生成
  for (let i = 0; i < pendingObjects.length; i++) {
    const objectName = pendingObjects[i];
    const style = STYLES[i % STYLES.length];
    const aspectRatio = ASPECT_RATIOS[i % ASPECT_RATIOS.length];

    console.log(`[ExplosionCron] [${i + 1}/${pendingObjects.length}] 生成中: ${objectName} (${style}, ${aspectRatio})`);

    const result = await generateSingleExplosion(objectName, style, aspectRatio);

    if (result) {
      // 新增到圖庫
      gallery.unshift(result);
      markObjectAsGenerated(objectName);
      successCount++;
      console.log(`[ExplosionCron] ✓ 成功: ${objectName}`);
    } else {
      failCount++;
      errors.push(objectName);
      console.error(`[ExplosionCron] ✗ 失敗: ${objectName}`);
    }

    // 避免 API 請求過快
    if (i < pendingObjects.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }

  // 儲存圖庫
  saveExplosionGallery(gallery);

  // 更新執行時間
  updateLastCronRun();

  const index = loadExplosionIndex();

  console.log(`[ExplosionCron] 任務完成: 成功 ${successCount}, 失敗 ${failCount}`);

  return NextResponse.json({
    status: "completed",
    message: `成功生成 ${successCount} 組爆炸圖`,
    successCount,
    failCount,
    errors: failCount > 0 ? errors : undefined,
    totalGenerated: index.totalGenerated,
    gallerySize: gallery.length,
    lastRun: index.lastCronRun,
  });
}

// POST - 手動觸發（與 GET 相同）
export async function POST(request: NextRequest) {
  return GET(request);
}
